"""
docstring
"""

class GameException(BaseException):
    """
    Base class for all game exceptions.
    """

class GameExit(GameException): ...

class InvalidCommand(GameException): ...

class RoomNotFound(GameException): ...

class GameOver(GameException): ...

class ItemNotFound(GameException): ...

class ObjectNotFound(GameException): ...

class UnknownAction(GameException): ...