class GameException(BaseException): ...

class GameExit(GameException): ...

class GameOver(GameException): ...

class UnknownAction(GameException): ...

class ObjectNotFound(GameException): ...

class ActionNotPermitted(GameException): ...